language: python

os: linux

dist: bionic

python:
  - "3.6.10"
  - "3.7.7"
  - "3.8.2"

install:
  - pip install -r sample_python_project/requirements.txt
  - pip install -r sample_python_project/requirements-test.txt

jobs:
  fast_finish: true

script: cd sample_python_project && pytest
