name: Docker Image CI

on:
  pull_request:
    branches: [ main ]

jobs:

  build-docker-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag edumco/python-pipeline:latest
